# configuration
site_name: Note Pro
# repo
remote_name: origin
repo_url: https://github.com/MoonSmile1707/NotePro
edit_uri: blob/master/docs/
# search engine viewer
site_description: "Note Anything and Note Future."
site_author: "Moon Smile"
# serch engine
google_analytics: ["UA-36723568-3", "mkdocs.org"]
# network
dev_addr: "0.0.0.0:9091"
# set languages
lang:
  - en
  - fr
# copy at footer
copyright: "Moon Smile 2019"
# navigative page
nav:
  - Home: index.md
  - Daily Plans:
      - Version 1: daily-plans/plans-version-1.1.md
      - Version 2: daily-plans/plans-version-2.md
      - Version 3: daily-plans/plans-version-3.md
      - Soft Skills for Learning: daily-plans/soft-skills-for-learning.md
  - KnowLedge:
      - Principles:
          - S.O.L.I.D: knowledge/principles/s-o-l-i-d.md
      - Pattern:
          - Dependency Injection: knowledge/pattern/dependency-injection.md
          - Design Pattern: knowledge/pattern/design_pattern.md
          - Aggregate Pattern: knowledge/pattern/aggregate-pattern.md
          - The 7 mose important software design pattern: knowledge/pattern/the-7-most-important-software-design-patterns.md
      - Algorithms:
          - Analysis of Algorithms: knowledge/algorithms/analysis-of-algorithms.md
      - DevOps:
          - Circle CI:
              - Writing YAML: knowledge/dev-ops/circle-ci/writing-yaml.md
          - Docker:
              - Docker Network: knowledge/dev-ops/docker/docker-network.md
      - Web Development:
          - Basics:
              - Code Coverage: knowledge/web-development/basics/code-coverage.md
              - Regression Testing: knowledge/web-development/basics/regression-testing.md
              - Functional Testing: knowledge/web-development/basics/functional-testing.md
              - Integration Testing: knowledge/web-development/basics/integration-testing.md
              - Unit Testing: knowledge/web-development/basics/unit-testing.md
              - CSS HandBook: knowledge/web-development/basics/css-handbook.md
              - Introducing WebSockets: knowledge/web-development/basics/introducing-websockets.md
          - ASP.NET:
              - Introduction: knowledge/web-development/asp.net/introduction.md
              - NSwag: knowledge/web-development/asp.net/nswag.md
          - NodeJS:
              - Libuv: knowledge/web-development/nodejs/libuv.md
              - Overview of Blocking and Non-Blocking: knowledge/web-development/nodejs/overview-of-blocking-and-non-blocking.md
              - The Node.js Event Loop: knowledge/web-development/nodejs/what-is-the-event-loop.md
              - Get Started: knowledge/web-development/nodejs/get-started.md
          - Ruby On Rails:
              - Overview: knowledge/web-development/ruby-on-rails/overview.md
              - Rails Form Expand: knowledge/web-development/ruby-on-rails/rails-form-expand.md
              - Active Record Callbacks: knowledge/web-development/ruby-on-rails/rails-active-record-callbacks.md
              - Action View Form Helpers: knowledge/web-development/ruby-on-rails/action-view-form-helpers.md
      - Stories:
          - Skill Blog:
              - How to be a great programmer: knowledge/stories/skill-blog/how-to-be-a-great-programmer.md
              - What Javascript Developers can learn from C++: knowledge/stories/skill-blog/what-javascript-developers-learn-from-c++.md
              - What I learn from lauching a freelance writing business: knowledge/stories/skill-blog/what-i-learn-from-lauching-a-freelance-writing-bussiess.md
              - How code reviews work at Microsoft: knowledge/stories/skill-blog/how-code-reviews-work-at-microsoft.md
              - How to debug web apps with Firefox developer tools: knowledge/stories/skill-blog/how-to-debug-with-firefox.md
              - Beyond Coding - Soft skill to avoid projects failures: knowledge/stories/skill-blog/beyond-coding-soft-skill-to-avoid-projects-fails.md
              - 3 Things to do when you don't have computer science degree: knowledge/stories/skill-blog/3-things-to-do-when-you-dont-have-computers-science-degree.md
              - .NET Core is Future of .NET: knowledge/stories/skill-blog/net-core-is-future-of-net.md
              - Introducing .NET 5: knowledge/stories/skill-blog/introducing-net-5.md
              - Scraping Web With Nodejs: knowledge/stories/skill-blog/scraping-the-web-with-nodejs.md
              - Roadmap Web Developer 2019: knowledge/stories/skill-blog/roadmap-web-developer-2019.md
              - Tiny Go: knowledge/stories/skill-blog/tinygo.md
          - Dev Ops:
              - What is DevOps? Why do we need it?: knowledge/stories/devops-blog/what-is-devops-and-why-do-we-need-it.md
          - Computer Science:
              - What is between machine learning and AI: knowledge/stories/computer-science/what-is-different-between-machine-learning-and-ai.md
          - Blockchain:
              - Matic Developer Support Program: knowledge/stories/blockchain-blog/matic-developer-support-program.md
              - What Is Matic Network: knowledge/stories/blockchain-blog/what-is-matic-network.md
              - Plasma: knowledge/stories/blockchain-blog/plasma.md
          - Thinking In Art:
              - You Could Have Today Intead You Choose Tomorrow: knowledge/stories/thinking-in-art/you-could-have-today-instead-you-choose-tomorrow.md
              - How to quit your job and live your startup dream: knowledge/stories/thinking-in-art/how-to-quit-your-job-and-live-your-startup-dream.md
              - How two words can change your life: knowledge/stories/thinking-in-art/how-two-words-can-change-your-life.md
              - 4 Practical Things I do to stay positive: knowledge/stories/thinking-in-art/4-practical-things-i-do-to-stay-positive.md
          - Xamarin Blog:
              - Getting Started WorkManager: knowledge/stories/xamarin-blog/getting-started-workmanager.md
              - Sharing Files and Email Attachment: knowledge/stories/xamarin-blog/sharing-files-and-email-attachments.md
              - Add a Backend to Your App in 10 minutes: knowledge/stories/xamarin-blog/add-a-backend-to-your-app-in-10-minutes.md
              - Behavior In Xamarin Forms: knowledge/stories/xamarin-blog/behavior-xamarin.md
              - Shrinking Your Android App Size: knowledge/stories/xamarin-blog/shrinking-your-android-app-size.md
              - Mobile Tools for Designer: knowledge/stories/xamarin-blog/mobile-tools-for-designers.md
      - Mobile Development:
          - Overview: knowledge/mobile-development/overview.md
          - Xamarin:
              - Xamarin Forms Shell: knowledge/mobile-development/xamarin/xamarin-forms-shell.md
              - Controls Reference: knowledge/mobile-development/xamarin/controls-reference.md
              - Customizing ListView cell Appearence: knowledge/mobile-development/xamarin/customizing-listview-cell-appearance.md
              - Data Pages: knowledge/mobile-development/xamarin/data-pages.md
              - Data Pages Controls: knowledge/mobile-development/xamarin/data-pages-controls.md
              - Triggers: knowledge/mobile-development/xamarin/triggers.md
              - Themes: knowledge/mobile-development/xamarin/xamarin-forms-theme.md
              - Template:
                  - Overview: knowledge/mobile-development/xamarin/templates/overview.md
                  - Control Templates: knowledge/mobile-development/xamarin/templates/control-templates.md
                  - Data Templates: knowledge/mobile-development/xamarin/templates/data-templates.md
# configuration theme
# extra_css:
# extra_javascript:
# extra_templates:

theme:
  name: mkdocs
  custom_dir: notepro_theme
# extension
markdown_extensions:
  - toc:
      # permalink: true
      # separator: '_'
