site_name: Note Pro
nav:
  - Home: index.md
  - Daily Plans:
    - Version 1: daily-plans/plans-version-1.md
  - KnowLedge:
      - DevOps:
          - Circle CI:
              - Writing YAML: knowledge/dev-ops/circle-ci/writing-yaml.md
      - Web Development:
          - Ruby On Rails:
              - Rails Form Expand: knowledge/web-development/ruby-on-rails/rails-form-expand.md
theme:
  name: mkdocs
  custom_dir: notepro_theme
