site_name: Note Pro
nav:
  - Home: index.md
  - About: about.md
theme:
  name: readthedocs
  custom_dir: notepro_theme
  # name: readthedocs
  # highlightjs: true
  # hljs_languages:
  #   - yaml
  #   - rust

markdown_extensions:
  - toc:
      separator: "_"
      permalink: "#"
      baselevel: 1
