# configuration
site_name: Note Pro
# repo
remote_name: origin
repo_url: https://github.com/MoonSmile1707/NotePro
edit_uri: blob/master/docs/
# search engine viewer
site_description: "Note Anything and Note Future."
site_author: "Moon Smile"
# serch engine
google_analytics: ["UA-36723568-3", "mkdocs.org"]
# network
dev_addr: "0.0.0.0:9091"
# set languages
lang:
  - en
  - fr
# copy at footer
copyright: "Moon Smile 2019"
# navigative page
nav:
  - Home: index.md
  - Daily Plans:
      - Version 1: daily-plans/plans-version-1.md
  - KnowLedge:
      - DevOps:
          - Circle CI:
              - Writing YAML: knowledge/dev-ops/circle-ci/writing-yaml.md
      - Web Development:
          - Ruby On Rails:
              - Rails Form Expand: knowledge/web-development/ruby-on-rails/rails-form-expand.md
              - Active Record Callbacks: knowledge/web-development/ruby-on-rails/rails-active-record-callbacks.md
      - Stories:
          - Blockchain:
              - Matic Developer Support Program: knowledge/stories/blockchain-blog/matic-developer-support-program.md
              - What Is Matic Network: knowledge/stories/blockchain-blog/what-is-matic-network.md
              - Plasma: knowledge/stories/blockchain-blog/plasma.md
          - Thinking In Art:
              - You Could Have Today Intead You Choose Tomorrow: knowledge/stories/thinking-in-art/you-could-have-today-instead-you-choose-tomorrow.md
      - Mobile Development: 
        - Xamarin:
          - Controls Reference: knowledge/mobile-development/xamarin/controls-reference.md
          - Customizing ListView cell Appearence: knowledge/mobile-development/xamarin/customizing-listview-cell-appearance.md
          - Data Pages: knowledge/mobile-development/xamarin/data-pages.md
          - Data Pages Controls: knowledge/mobile-development/xamarin/data-pages-controls.md
          - Themes: knowledge/mobile-development/xamarin/xamarin-forms-theme.md
# configuration theme
# extra_css:
# extra_javascript:
# extra_templates:

theme:
  name: mkdocs
  custom_dir: notepro_theme
# extension
markdown_extensions:
  - toc:
      # permalink: true
      # separator: '_'
